git_branch: master

gunicorn_num_workers: 3
gunicorn_max_requests: 0

# Database settings

db_host: "{{ hostvars[groups['postgresql-servers'][0]]['ansible_eth1']['ipv4']['address'] }}"
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: password

django_settings_file: "{{ application_name }}.settings"
django_secret_key: "{{ django_secret_key }}"

ssl_dest_dir: /etc/ssl

run_django_sync_db: yes
run_django_db_migrations: yes
run_django_collectstatic: yes

openssl_params: /CN=data-adviser.com/O=Artyom Boyko/C=UA

celery_num_workers: 2

rabbitmq_admin_user: admin
rabbitmq_admin_password: password

rabbitmq_application_user: "{{ application_name }}"
rabbitmq_application_password: password

broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@{{ hostvars[groups['queue-servers'][0]]['ansible_eth1']['ipv4']['address'] }}:5672/{{ application_name }}"
