git_branch: master

gunicorn_num_workers: 3
gunicorn_max_requests: 0

# Database settings

db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_host: "{{ production_servers[groups['postgresql-servers'][0]]['ip'] }}"

django_settings_file: "{{ application_name }}.settings"
django_secret_key: "{{ django_secret_key }}"

ssl_dest_dir: /etc/ssl

run_django_sync_db: yes
run_django_db_migrations: yes
run_django_collectstatic: yes

openssl_params: /CN=data-adviser.com/O=Artyom Boyko/C=UA/ST=Kievska Obl/L=Slavutich/O=NA/OU=NA/CN=data-adviser.com/emailAddress=artyomboyko@gmail.com

celery_num_workers: 2

rabbitmq_admin_user: admin
rabbitmq_application_user: "{{ application_name }}"

broker_url: "amqp://{{ rabbitmq_application_user }}:{{ rabbitmq_application_password }}@{{ production_servers[groups['queue-servers'][0]]['ip'] }}:5672//{{ application_name }}"
