language: python
python: 3.5

sudo: false
env:
- TOXENV=pypy3
- TOXENV=py34
- TOXENV=py35

install:
    - pip install -U -r requirements/test.txt
    - npm install jslint
script:
    - tox
after_success:
    - codecov -f src/analytics/coverage.xml src/collector/coverage.xml