language: python
python: 3.5

sudo: false
env:
- TOXENV=pypy
- TOXENV=py34
- TOXENV=py35

install:
    - pip install -U tox codecov
    - npm install jslint
script:
    - tox
after_success:
    - codecov -f src/analytics/coverage.xml src/collector/coverage.xml