language: python
python: 3.5

sudo: false
env:
- TOXENV=pypy
- TOXENV=py33
- TOXENV=py34
- TOXENV=py35

install:
    - pip install -U tox codecov
script:
    - tox
after_success:
    - codecov --file src/analytics/coverage.xml --file src/collector/coverage.xml