language: python
python: 3.5

sudo: true
env:
- TOXENV=pypy
- TOXENV=py33
- TOXENV=py34
- TOXENV=py35

install:
    - pip install -U tox codecov
    - sudo apt-get install gwenhywfar-tools
script:
    - tox
after_success:
    - xmlmerge src/collector/coverage.xml src/collector/coverage.xml -o coverage.xml
    - codecov --file coverage.xml