---

- hosts: localhost
  vars_files:
    - env_vars/digitalocean.yml
    - env_vars/private.yml

  tasks:
    - name: Check ssh key
      ignore_errors: yes
      digital_ocean: >
        state=present
        command=ssh
        name="{{ do_ssh_name }}"
        ssh_pub_key="{{ do_ssh_pub_key }}"
        api_token="{{ digitalocean_api_key }}"

    - name: Create droplets
      digital_ocean: >
        state=present
        command=droplet
        name={{ item.value.name }}
        private_networking=yes
        size_id={{ item.value.size }}
        region_id={{ do_region }}
        image_id={{ do_image }}
        api_token="{{ digitalocean_api_key }}"
        wait_timeout=500
      with_dict: "{{ do_droplets }}"
      register: registered_droplets

    - debug: msg="ID is {{ item.droplet.id }}, IP is {{ item.droplet.ip_address }}"
      with_items: "{{ registered_droplets.results }}"

    - name: Add new droplet to inventory
      add_host: >
        name="{{ item.item.value.name }}"
        groups=digitalocean_hosts
        ansible_ssh_host="{{ item.droplet.ip_address }}"
        ansible_ssh_user=root
        ansible_ssh_private_key_file="{{ do_ssh_private_key }}"
      with_items: "{{ registered_droplets.results }}"