---

- hosts: localhost
  vars_files:
    - env_vars/digitalocean.yml
    - env_vars/private.yml

  tasks:
    - name: Delete droplets
      digital_ocean: >
        state=deleted
        command=droplet
        id={{ item.value.id }}
        name={{ item.value.name }}
        size_id={{ item.value.size }}
        region_id={{ do_region }}
        image_id={{ do_image }}
        api_token="{{ digitalocean_api_key }}"
        wait_timeout=500
      with_dict: "{{ do_droplets }}"