---

- hosts: localhost
  vars_files:
    - env_vars/digitalocean.yml
    - env_vars/private.yml
    - production_hosts.yml

  tasks:
    - name: Delete droplets
      digital_ocean: >
        state=absent
        id={{ item.value.id }}
        api_token="{{ digitalocean_api_key }}"
        wait_timeout=500
      with_dict: "{{ production_servers }}"