---

- hosts: localhost
  vars_files:
    - env_vars/digitalocean.yml
    - env_vars/private.yml

  tasks:
    - name: Check ssh key
      ignore_errors: yes
      digital_ocean: >
        state=present
        command=ssh
        name="{{ do_ssh_name }}"
        ssh_pub_key="{{ do_ssh_pub_key }}"
        api_token="{{ digitalocean_api_key }}"

    - name: Get ssh keys
      uri:
        status_code: 200
        url: https://api.digitalocean.com/v2/account/keys
        method: GET
        body_format: json
        HEADER_Authorization: "Bearer {{ digitalocean_api_key }}"
      register: json_response

    - name: Search key
      set_fact: ssh_key_id="{{ item.id }}"
      when: item.name == do_ssh_name
      with_items: "{{ json_response.json.ssh_keys }}"

    - fail: msg="SSH key not found"
      when: ssh_key_id is not defined

    - name: Create droplets
      digital_ocean: >
        state=present
        command=droplet
        name={{ item.name }}
        private_networking=yes
        ssh_key_ids={{ ssh_key_id }}
        size_id={{ item.size }}
        region_id={{ do_region }}
        unique_name=yes
        image_id={{ do_image }}
        api_token="{{ digitalocean_api_key }}"
        wait_timeout={{ do_timeout }}
      with_items: "{{ do_droplets }}"
      register: registered_droplets

    - local_action: template src=templates/hosts_template.j2 dest="{{ inventory_dir }}/production_hosts.yml"
    - include_vars: production_hosts.yml

    - name: Create DNS domains
      uri:
        status_code: 201
        url: https://api.digitalocean.com/v2/domains
        method: POST
        HEADER_Authorization: "Bearer {{ digitalocean_api_key }}"
        body_format: json
        body: "{\"name\": \"{{ item.key }}\", \"ip_address\": \"{{ item.value.public }}\"}"
      with_dict: "{{ production_servers }}"

    - name: Create DNS records
      uri:
        status_code: 201
        url: "https://api.digitalocean.com/v2/domains/{{ item.host }}/records"
        method: POST
        HEADER_Authorization: "Bearer {{ digitalocean_api_key }}"
        body_format: json
        body: "{\"type\": \"{{ item.type }}\", \"name\": \"{{ item.name }}\", \"data\": \"{{ item.data }}\"}"
      with_items: "{{ do_dns }}"

    - debug: msg="ID is {{ item.droplet.id }}, IP is {{ item.droplet.ip_address }}"
      with_items: "{{ registered_droplets.results }}"

    - local_action: template src=templates/inventory_template.j2 dest="{{ inventory_dir }}/production"
