---

#- include: base.yml
- include: dbservers.yml
- include: webservers.yml
#- include: cacheservers.yml
- include: celeryservers.yml
#- include: collectorservers.yml
#- include: elasticservers.yml
#- include: queueservers.yml