---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: django-servers
  vars_files:
    - env_vars/base.yml
    - env_vars/private.yml
    - env_vars/{{ env }}.yml
  pre_tasks:
    - include_vars: "production_hosts.yml"
  roles:
    - app
    - web