# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements/test.txt"

# Gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps

nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/{{ project_name }}/src/{{ application_name }}/{{ application_name }}/assets/"
nginx_media_dir: "{{ virtualenv_path }}/media/"
