- name: Ensure OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - openssl
    - libssl-dev

- name: install apt packages
  apt: name={{ item }} update_cache={{ update_apt_cache }}
  with_items:
      - git
      - build-essential
      - python-dev
      - python-pip
      - python-setuptools
      - libjpeg-dev

- name: Install virtualenv
  pip: name=virtualenv

- name: set locale.gen file
  locale_gen: name=en_US.UTF-8 state=present

- name: locale fix
  lineinfile: dest=/etc/environment line="LC_ALL="en_US.utf-8"" state=present
