- include: install_additional_packages.yml

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_git_repo.yml
  tags: deploy

- include: set_file_permissions.yml
  tags: deploy
