- name: Create the Supervisor config file
  template: src=supervisor_config.j2
            dest=/etc/supervisor/conf.d/{{ application_name }}.conf
            backup=yes

- name: Supervisor check app
  supervisorctl: name={{ application_name }} state=present

- name: Supervisor restart app
  supervisorctl: name={{ application_name }} state=restarted

- name: Supervisor check flower
  supervisorctl: name=flower state=present

- name: Supervisor restart flower
  supervisorctl: name=flower state=restarted