- name: Install Nginx
  apt: name=nginx update_cache={{ update_apt_cache }} state=installed
  tags: packages

- stat: path={{ ssl_dest_dir }}/{{ application_name }}.csr
  register: csr_exists

- name: Generate SSL certificate
  command: openssl req -subj '{{ openssl_params }}' -new -newkey rsa:2048 -nodes -keyout {{ ssl_dest_dir }}/{{ application_name }}.key -out {{ ssl_dest_dir }}/{{ application_name }}.csr
  when: csr_exists.stat.exists == False
  notify: restart nginx

- name: Create the Nginx configuration file
  template: src=nginx_https_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes
  notify: reload nginx
  when: vagrant is not defined

- name: Create the Nginx configuration file
  template: src=nginx_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes
  notify: reload nginx
  when: vagrant is defined

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ application_name }} dest=/etc/nginx/sites-enabled/{{ application_name }} owner=root group=root state=link
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
